INSERT INTO LOCALIDADE(ID,DESCRICAO) VALUES(1,'A');
INSERT INTO LOCALIDADE(ID,DESCRICAO) VALUES(2,'B');
INSERT INTO LOCALIDADE(ID,DESCRICAO) VALUES(3,'C');
INSERT INTO LOCALIDADE(ID,DESCRICAO) VALUES(4,'D');
INSERT INTO LOCALIDADE(ID,DESCRICAO) VALUES(5,'E');

INSERT INTO CAMINHO(CAMINHO_ORIGEM,CAMINHO_DESTINO,CUSTO) values(1,2,10);
INSERT INTO CAMINHO(CAMINHO_ORIGEM,CAMINHO_DESTINO,CUSTO) values(2,4,15);
INSERT INTO CAMINHO(CAMINHO_ORIGEM,CAMINHO_DESTINO,CUSTO) values(1,3,20);
INSERT INTO CAMINHO(CAMINHO_ORIGEM,CAMINHO_DESTINO,CUSTO) values(3,4,30);
INSERT INTO CAMINHO(CAMINHO_ORIGEM,CAMINHO_DESTINO,CUSTO) values(2,5,50);
INSERT INTO CAMINHO(CAMINHO_ORIGEM,CAMINHO_DESTINO,CUSTO) values(4,5,30);


